#server port 설정
server:
  port: 9001

#jsp를 하기위한 세팅
spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/board/
#      suffix: .jsp 
  devtools:
    livereload:
      enabled: true
      
#mysql setting      
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/bitcamp?serverTimezone=Asia/Seoul
    username: angel
    password: 1234
    
#mybatis
mybatis:
  type-aliases-package: data.mapper, data.dto
  mapper-locations:
  - /mapper/**/*.xml