#server port 설정
server:
  port: 9001

#jsp를 하기위한 세팅
spring:
  mvc:
    view:
      prefix: /WEB-INF/board/
      suffix: .jsp 
  devtools:
    livereload:
      enabled: true
      
#mysql setting      
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/bitcamp?serverTimezone=Asia/Seoul
    username: angel
    password: 1234
    
#JPA setting
  jpa:
    hibernate:
      ddl-auto: update  #기존테이블이 있으면 업데이트 되도록
    generate-ddl: true 
    show-sql: true  #콘솔장에 sql문 찍히도록
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect 

