/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-04-25 03:36:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.day0422;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class GuestMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.0.js\"></script>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Gamja+Flower&family=Gowun+Dodum&family=Jua&family=Lobster&family=Nanum+Pen+Script&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("div.header {\r\n");
      out.write("	width: 80%;\r\n");
      out.write("	height: 110px;\r\n");
      out.write("	line-height: 100px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 35px;\r\n");
      out.write("	font-family: 'Lobster';\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	border: 10px solid gold;\r\n");
      out.write("	margin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.all {\r\n");
      out.write("	width: 1100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.inform {\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	font-family: 'Jua';\r\n");
      out.write("	float: left;\r\n");
      out.write("	width: 480px;\r\n");
      out.write("	height: auto;\r\n");
      out.write("	border: 5px solid gray;\r\n");
      out.write("	padding: 20px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.list {\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	font-family: 'Jua';\r\n");
      out.write("	float: right;\r\n");
      out.write("	width: 600px;\r\n");
      out.write("	height: auto;\r\n");
      out.write("	border: 5px solid gray;\r\n");
      out.write("	padding: 20px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img.imgphoto {\r\n");
      out.write("	width: 55px;\r\n");
      out.write("	height: 55px;\r\n");
      out.write("	margin-right: 3px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".select {\r\n");
      out.write("	border: 2px solid black;\r\n");
      out.write("	box-shadow: 3px 3px gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span.mod, span.del{\r\n");
      out.write("	margin-left: 10px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span.day{\r\n");
      out.write("	float: right;\r\n");
      out.write("	color: #999;\r\n");
      out.write("	font-size : 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img.avata{\r\n");
      out.write("	width: 80px;}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(function() {\r\n");
      out.write("		list(); //처음 시작 시 목록 출력\r\n");
      out.write("\r\n");
      out.write("		//저장 이벤트\r\n");
      out.write("		$(\".btnsave\").click(function() {\r\n");
      out.write("			//폼 전체 데이터를 읽어서 insert.jsp 로 보낸다\r\n");
      out.write("			//성공 후 list() 다시 호출 후, 입력값 초기화\r\n");
      out.write("\r\n");
      out.write("			var fdata = $(\"#frm\").serialize();\r\n");
      out.write("\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type : \"post\",\r\n");
      out.write("				dataType : \"html\",\r\n");
      out.write("				url : \"insert.jsp\",\r\n");
      out.write("				data : fdata,\r\n");
      out.write("				success : function() {\r\n");
      out.write("					//목록 다시 출력\r\n");
      out.write("					list();\r\n");
      out.write("					//입력값 지우기 //text, number만..\r\n");
      out.write("					$(\"#writer\").val(\"\"); //초기값 줌\r\n");
      out.write("					$(\"#pass\").val(\"\");\r\n");
      out.write("					$(\"#content\").val(\"\");\r\n");
      out.write("\r\n");
      out.write("					$(\"#avata\").val(\"1\");\r\n");
      out.write("					$(\"img.imgphoto\").removeClass(\"select\");\r\n");
      out.write("					$(\"img.imgphoto:first\").addClass(\"select\");\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		//삭제 이벤트 \r\n");
      out.write("		$(document).on(\"click\",\"span.del\",function(){\r\n");
      out.write("			var num = $(this).attr(\"num\");\r\n");
      out.write("			//비번은 입력\r\n");
      out.write("			var pass = prompt(\"이 글에 대한 비밀번호를 입력해주세요\");\r\n");
      out.write("			console.log(num+\",\"+pass);\r\n");
      out.write("			//취소 클릭하거나 비번을 입력 안했을 경우 함수 종료\r\n");
      out.write("			if(pass==null || pass.length==0){\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type:\"get\",\r\n");
      out.write("				dataType: \"json\",\r\n");
      out.write("				data:{\"num\":num, \"pass\":pass},\r\n");
      out.write("				url:\"delete.jsp\",\r\n");
      out.write("				success : function(data){\r\n");
      out.write("					if(data.result == 'true'){\r\n");
      out.write("						alert(\"삭제되었습니다\");\r\n");
      out.write("						location.reload(); //새로고침\r\n");
      out.write("					}else{\r\n");
      out.write("						alert(\"비번이 맞지 않습니다\");\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		//수정 이벤트\r\n");
      out.write("		$(document).on(\"click\",\"span.mod\",function(){\r\n");
      out.write("			var num = $(this).attr(\"num\");\r\n");
      out.write("			//비번은 입력\r\n");
      out.write("			var pass = prompt(\"이 글에 대한 비밀번호를 입력해주세요\");\r\n");
      out.write("			console.log(num+\",\"+pass);\r\n");
      out.write("			//취소 클릭하거나 비번을 입력 안했을 경우 함수 종료\r\n");
      out.write("			if(pass==null || pass.length==0){\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type:\"get\",\r\n");
      out.write("				dataType: \"json\",\r\n");
      out.write("				data:{\"num\":num, \"pass\":pass},\r\n");
      out.write("				url:\"equalpass.jsp\",\r\n");
      out.write("				success : function(data){\r\n");
      out.write("					if(data.result == 'true'){\r\n");
      out.write("						//비번이 맞으면 수정폼으로 이동\r\n");
      out.write("						location.href='updateform.jsp?num='+num;\r\n");
      out.write("					}else{\r\n");
      out.write("						alert(\"비번이 맞지 않습니다\");\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	});//$function close\r\n");
      out.write("	\r\n");
      out.write("	function list() {\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : \"get\",\r\n");
      out.write("			dataType : \"json\",\r\n");
      out.write("			url : \"list.jsp\",\r\n");
      out.write("			success : function(data) {\r\n");
      out.write("				var s = \"\";\r\n");
      out.write("\r\n");
      out.write("				$.each(data, function(i, elt) {\r\n");
      out.write("					s += \"<table class='table'>\";\r\n");
      out.write("					s += \"<tr><td>\";\r\n");
      out.write("					s += \"<b>\" + elt.writer + \"</b>\";\r\n");
      out.write("					s +=\"<span class='mod' num=\"+elt.num+\">수정</span>\";\r\n");
      out.write("					s +=\"<span class='del' num=\"+elt.num+\">삭제</span>\";\r\n");
      out.write("					s +=\"<span class='day'>\"+elt.writeday+\"</span>\";\r\n");
      out.write("					s += \"</td></tr>\";\r\n");
      out.write("					\r\n");
      out.write("					s += \"<tr><td>\";\r\n");
      out.write("					s += \"<img src='../avata/s\"+elt.avata+\".JPG' class='avata' align=left hspace=20>\";\r\n");
      out.write("					s += \"<pre>\"+elt.content+\"</pre>\";\r\n");
      out.write("				\r\n");
      out.write("						\r\n");
      out.write("					s += \"</td></tr>\"\r\n");
      out.write("					s += \"</table><br><br>\";\r\n");
      out.write("					\r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("				$(\"div.list\").html(s);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"header\">Guest Ajax Test</div>\r\n");
      out.write("	<div class=\"all\">\r\n");
      out.write("		<div class=\"inform\">\r\n");
      out.write("			<form id=\"frm\" class=\"form-inline\">\r\n");
      out.write("				<table class=\"table\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td width=\"350\">작성자 : <input type=\"text\" id=\"writer\"\r\n");
      out.write("							name=\"writer\" class=\"form-control\" style=\"width: 100px;\">\r\n");
      out.write("\r\n");
      out.write("							비밀번호 : <input type=\"password\" id=\"pass\" name=\"pass\"\r\n");
      out.write("							class=\"form-control\" style=\"width: 100px;\">\r\n");
      out.write("						</td>\r\n");
      out.write("						<td rowspan=\"3\" style=\"cursor: pointer; background-color: orange;\"\r\n");
      out.write("							align=\"center\" valign=\"middle\" class=\"btnsave\">저장</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td><textarea id=\"content\" name=\"content\"\r\n");
      out.write("								style=\"width: 100%; height: 100px;\"></textarea></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td><input type=\"hidden\" id=\"avata\" name=\"avata\" value=\"1\"><br>\r\n");
      out.write("							");

							for (int i = 1; i <= 10; i++) {
							
      out.write(" <img src=\"../avata/s");
      out.print(i);
      out.write(".JPG\" class=\"imgphoto\" idx=\"");
      out.print(i);
      out.write("\">\r\n");
      out.write("							");

							if (i == 5) {
							
      out.write(" <br> ");

 }
 }
 
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("		//일단 첫번째 이미지에 .select 적용\r\n");
      out.write("		$(\"img.imgphoto\").eq(0).addClass(\"select\");\r\n");
      out.write("\r\n");
      out.write("		//아바타 클릭시 idx값을 얻어서 #avata에 출력\r\n");
      out.write("		//클릭한 이미지에만 .select 가 적용되도록 하기 \r\n");
      out.write("		$(\"img.imgphoto\").click(function() {\r\n");
      out.write("			$(this).siblings().removeClass(\"select\");\r\n");
      out.write("			$(this).addClass(\"select\");\r\n");
      out.write("			$(\"#avata\").val($(this).attr(\"idx\"));\r\n");
      out.write("		});\r\n");
      out.write("	</script></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"list\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
