/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-04-22 02:18:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.day0420;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ShopDetailPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.0.js\"></script>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Gamja+Flower&family=Gowun+Dodum&family=Jua&family=Lobster&family=Nanum+Pen+Script&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");

String num = request.getParameter("num");

      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("div.detail {\r\n");
      out.write("	margin-top: 100px;\r\n");
      out.write("	margin-left: 200px;\r\n");
      out.write("	font-size: 25px;\r\n");
      out.write("	font-family: 'Jua';\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(function() {\r\n");
      out.write("		init(); //처음 시작시 dto 데이터 넣어주기\r\n");
      out.write("\r\n");
      out.write("		//메인페이지로 가는 이벤트\r\n");
      out.write("		$(\"#btnmain\").click(function() {\r\n");
      out.write("			history.back(); //이전 페이지로 이동\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		//삭제\r\n");
      out.write("		$(\"#btndelete\").click(function() {\r\n");
      out.write("\r\n");
      out.write("			var ans = confirm(\"삭제하려면 [확인] 버튼을 눌러주세요\");\r\n");
      out.write("			if (ans) {\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					type : \"get\",\r\n");
      out.write("					dataType : \"html\",\r\n");
      out.write("					url : \"delete.jsp\",\r\n");
      out.write("					data : {\r\n");
      out.write("						\"num\" : $(\"#num\").val()\r\n");
      out.write("					},\r\n");
      out.write("					success : function() {\r\n");
      out.write("						//ShopJson.html 로 이동\r\n");
      out.write("						location.href = \"ShopJson.html\";\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		//수정버튼 (맨 아래 수정 modal)\r\n");
      out.write("		$(\"#btnupdate\").click(function() {\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type : \"get\",\r\n");
      out.write("				dataType : \"json\",\r\n");
      out.write("				url : \"DetailJson.jsp\",\r\n");
      out.write("				data : {\r\n");
      out.write("					\"num\" : $(\"#num\").val()\r\n");
      out.write("				},\r\n");
      out.write("				success : function(data) {\r\n");
      out.write("					$(\"#usangpum\").val(data.sangpum);\r\n");
      out.write("					$(\"#uprice\").val(data.price);\r\n");
      out.write("					$(\"#ucnt\").val(data.cnt);\r\n");
      out.write("					$(\"#uphoto\").val(data.photo);\r\n");
      out.write("					$(\"#umyphoto\").attr(\"src\", data.photo);\r\n");
      out.write("					$(\"#ucolor\").val(data.color);\r\n");
      out.write("					$(\"#uipgoday\").val(data.ipgoday);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			$(\"#myModal\").modal();\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		$(\"#ubtnupdate\").click(function() {\r\n");
      out.write("			//전체 폼 데이터 읽기\r\n");
      out.write("			var fdata = $(\"#ufrm\").serialize();\r\n");
      out.write("			//alert(fdata);\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type : \"post\",\r\n");
      out.write("				dataType : \"html\",\r\n");
      out.write("				url : \"update.jsp\",\r\n");
      out.write("				data : fdata,\r\n");
      out.write("				success : function() {\r\n");
      out.write("					location.reload(); //새로고침\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	}); //$function close\r\n");
      out.write("\r\n");
      out.write("	function init() {\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : \"get\",\r\n");
      out.write("			dataType : \"json\",\r\n");
      out.write("			url : \"DetailJson.jsp\",\r\n");
      out.write("			data : {\r\n");
      out.write("				\"num\" : $(\"#num\").val()\r\n");
      out.write("			},\r\n");
      out.write("			success : function(data) {\r\n");
      out.write("				$(\"#photo\").attr(\"src\", data.photo);\r\n");
      out.write("				$(\"#photo\").css(\"border\", \"4px solid gray\");\r\n");
      out.write("				$(\"#sangpum\").text(data.sangpum);\r\n");
      out.write("				$(\"#price\").text(data.price + \"원\");\r\n");
      out.write("				$(\"#color\").text(data.color);\r\n");
      out.write("				$(\"#color\").css({\r\n");
      out.write("					\"background-color\" : data.color,\r\n");
      out.write("					\"float\" : \"right\"\r\n");
      out.write("				});\r\n");
      out.write("				$(\"#cnt\").text(data.cnt + \"개\");\r\n");
      out.write("				$(\"#ipgoday\").text(data.ipgoday);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<input type=\"hidden\" id=\"num\" value=\"");
      out.print(num);
      out.write("\">\r\n");
      out.write("	<div class=\"detail\">\r\n");
      out.write("		<table class=\"table table-bordered\" style=\"width: 600px;\">\r\n");
      out.write("			<caption>\r\n");
      out.write("				<h1>상품 상세 페이지</h1>\r\n");
      out.write("			</caption>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td width=\"300\"><img src=\"\" width=\"300\" height=\"400\" id=\"photo\">\r\n");
      out.write("				</td>\r\n");
      out.write("				<td>\r\n");
      out.write("					<h2>\r\n");
      out.write("						상품명 : <span id=\"sangpum\"></span>\r\n");
      out.write("					</h2>\r\n");
      out.write("					<h2>\r\n");
      out.write("						색 상 :\r\n");
      out.write("						<div id=\"color\"></div>\r\n");
      out.write("					</h2>\r\n");
      out.write("					<h2>\r\n");
      out.write("						가 격 : <span id=\"price\"></span>\r\n");
      out.write("					</h2>\r\n");
      out.write("					<h2>\r\n");
      out.write("						수 량 : <span id=\"cnt\"></span>\r\n");
      out.write("					</h2>\r\n");
      out.write("					<h2>\r\n");
      out.write("						입고일 : <span id=\"ipgoday\"></span>\r\n");
      out.write("					</h2>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td colspan=\"2\" align=\"center\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-success\" style=\"width: 120px;\"\r\n");
      out.write("						id=\"btnmain\">메인</button>\r\n");
      out.write("\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-info\" style=\"width: 120px;\"\r\n");
      out.write("						id=\"btnupdate\" num=");
      out.print(num);
      out.write(">수정</button>\r\n");
      out.write("\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-danger\" style=\"width: 120px;\"\r\n");
      out.write("						id=\"btndelete\" num=");
      out.print(num);
      out.write(">삭제</button>\r\n");
      out.write("				</td>\r\n");
      out.write("		</table>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- 수정 다이얼로그 Modal -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("		<div class=\"modal-dialog\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Modal content-->\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("					<h4 class=\"modal-title\">상품 수정</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("					<!-- Modal Body 부분에 수정폼 넣기 -->\r\n");
      out.write("					<p>\r\n");
      out.write("					<form action=\"#\" id=\"ufrm\" class=\"form-inline\">\r\n");
      out.write("						<input type=\"hidden\" id=\"unum\" name=\"unum\" value=\"");
      out.print(num);
      out.write("\">\r\n");
      out.write("						<table class=\"table table-bordered\" style=\"width: 400px;\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th bgcolor=\"pink\" style=\"width: 100px;\">상품명</th>\r\n");
      out.write("								<td><input type=\"text\" id=\"usangpum\" name=\"usangpum\"\r\n");
      out.write("									class=\"form-control\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th bgcolor=\"pink\" style=\"width: 100px;\">상품사진</th>\r\n");
      out.write("								<td><select id=\"uphoto\" name=\"uphoto\" class=\"form-control\"\r\n");
      out.write("									style=\"width: 120px;\">\r\n");
      out.write("										<script type=\"text/javascript\">\r\n");
      out.write("											var data = [ \"라운트티\", \"블랙원피스\",\r\n");
      out.write("													\"화이트원피스\", \"도트원피스\", \"블랙조끼\",\r\n");
      out.write("													\"꽃무늬원피스\", \"프릴원피스\", \"반팔원피스\",\r\n");
      out.write("													\"레이스원피스\", \"블랙코트\", \"체크쿠션\" ];\r\n");
      out.write("											var s = \"\";\r\n");
      out.write("											for (i = 1; i <= 10; i++) {\r\n");
      out.write("												s += \"<option value='../image2/\"\r\n");
      out.write("														+ (i + 1) //11.jpg\r\n");
      out.write("														+ \".jpg'>\"\r\n");
      out.write("														+ data[i]\r\n");
      out.write("														+ \"</option>\";\r\n");
      out.write("											}\r\n");
      out.write("											document.write(s);\r\n");
      out.write("										</script>\r\n");
      out.write("								</select> <img src=\"\" id=\"umyphoto\" width=\"60\" height=\"60\"> <script>\r\n");
      out.write("								\r\n");
      out.write("									//변경시 이벤트\r\n");
      out.write("									$(\"#uphoto\").change(\r\n");
      out.write("											function() {\r\n");
      out.write("												$(\"#umyphoto\").attr(\"src\",\r\n");
      out.write("														$(this).val());\r\n");
      out.write("											});\r\n");
      out.write("								</script></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th bgcolor=\"pink\" style=\"width: 100px;\">색상</th>\r\n");
      out.write("								<td><input type=\"color\" id=\"ucolor\" name=\"ucolor\"\r\n");
      out.write("									class=\"form-control\" value=\"#ffcccc\" style=\"width: 80px;\">\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th bgcolor=\"pink\" style=\"width: 100px;\">단가</th>\r\n");
      out.write("								<td><input type=\"text\" id=\"uprice\" name=\"uprice\"\r\n");
      out.write("									class=\"form-control\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th bgcolor=\"pink\" style=\"width: 100px;\">수량</th>\r\n");
      out.write("								<td><input type=\"number\" id=\"ucnt\" name=\"ucnt\"\r\n");
      out.write("									class=\"form-control\" min=\"1\" max=\"5\" value=\"1\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th bgcolor=\"pink\" style=\"width: 100px;\">입고일</th>\r\n");
      out.write("								<td><input type=\"date\" id=\"uipgoday\" name=\"uipgoday\"\r\n");
      out.write("									class=\"form-control\" value=\"2022-04-20\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td colspan=\"2\" align=\"center\">\r\n");
      out.write("									<button type=\"button\" class=\"btn btn-info\"\r\n");
      out.write("										style=\"width: 130px;\" id=\"ubtnupdate\" data-dismiss=\"modal\">DB수정</button>\r\n");
      out.write("								</td>\r\n");
      out.write("						</table>\r\n");
      out.write("					</form>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
